name: tutorial-local-llm
channels:
    - conda-forge
dependencies:
    - python=3.12.*
    - evidently=0.7.*
    - huggingface_hub=0.36.*
    - instructor
    - jupyter=1.1.*
    - jupyterlab=4.5.*
    - jupyterlab_execute_time
    - langchain-anthropic
    - langchain-google-genai
    - langchain-huggingface
    - langchain-mistralai
    - langchain-ollama
    - langchain-openai
    - llama-index=0.12.*
    - llama-index-core=0.12.*
    - llama.cpp
    - matplotlib=3.10.*
    - nbdime=4.0.*
    - ollama=0.13.*
    - ollama-python=0.6.*
    - openai=1.109.*
    - pandas=2.3.*
    - pydantic=2.12.*
    - pip:
        - deepeval==3.7.*
        - llama-index-llms-ollama
        - lm-eval==0.4.*
